In [1]:
from modules.fundamentals import Dimensions
import numpy as np
import numba
from numba.experimental import jitclass
#from classes import Field

In [111]:
dim = 3
dims = Dimensions(x=dim, y=dim, z=dim)

In [3]:
testdata = np.zeros((2,10),float)
print(testdata)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [112]:
@jitclass(
    [
        ("x", numba.float32[:, :, :]),
        ("y", numba.float32[:, :, :]),
        ("z", numba.float32[:, :, :]),
    ]
)
class Field(object):
    """This class creates a field in three directions.

    Attributes:
        x: Field strength in the x-direction
        y: Field strength in the y-direction
        z: Field strength in the z-direction
    """

    def __init__(self, dimensions, initial_value):
        """Construct a Field object with an
            *x*, *y*, and *z* component

        Size of array generated is x_cells by y_cells by z_cells
        with given initial_value
        """

        self.x = (
            np.ones((dimensions.x, dimensions.y, dimensions.z), dtype=np.float32)
            * initial_value
        )
        self.y = (
            np.ones((dimensions.x, dimensions.y, dimensions.z), dtype=np.float32)
            * initial_value
        )
        self.z = (
            np.ones((dimensions.x, dimensions.y, dimensions.z), dtype=np.float32)
            * initial_value
        )

    def __add__(self, other):
        return self.x + other.x, self.y + other.y, self.z + other.z

In [121]:
print(str(np.ones((2,3))))

[[1. 1. 1.]
 [1. 1. 1.]]


In [114]:
a = Field(dims,1)
b = Field(dims,2)

In [115]:
c = a + b

In [38]:
a = [1,2,3]

In [22]:
print(a)

[1, 2, 3]


In [23]:
print(*a)

1 2 3


In [24]:
type(*a)

TypeError: type.__new__() argument 1 must be str, not int

In [25]:
str(a)

'[1, 2, 3]'

In [47]:
class Student: 
    def __init__(self,name, house) -> None:
        self.name = name
        self.house = house
        
    def __str__(self):
        return f"{self.name} is in {self.house}"
    


In [65]:
student = Student(np.array([1,2,3]), "Gryffindor")

In [66]:
print(student)

[1 2 3] is in Gryffindor


In [61]:
student.name

[1, 2, 3]

In [62]:
type(a.x)

numpy.ndarray

In [63]:
print(a.x)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [135]:
def test1(a,b):
    return "1"

def test2(a,b,c):
    return "2"

def assign(a):
    if a == 1: 
        args = [2,3]
        return test1, args
    if a == 2: 
        args = [2,3,1]
        return test2, args
    
    
test, args = assign(a=2)

print(args)
test(*args)

[2, 3, 1]


'2'

In [136]:
def function():
    return 1, 2, 3

In [141]:
ff = *function()

SyntaxError: can't use starred expression here (3734479321.py, line 1)

In [140]:
*ff

SyntaxError: can't use starred expression here (3828097604.py, line 1)